<?php
/**
 * Title: Events - Default Footer
 * Slug: events-directory/footer-default
 * Categories: blockstrap-site-footer
 * Viewport Width: 1280
 */

$section_img_url = esc_url( get_theme_file_uri( 'assets/images/section-bg-3.png' ) ); /* <?php echo esc_attr( $section_img_url ); ?> */
$logo_img_url = esc_url( get_theme_file_uri( 'assets/images/logo-no-background.png' ) ); /* <?php echo esc_attr( $logo_img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"#2e0761","bg_image":"<?php echo esc_attr( $section_img_url ); ?>","bg_image_id":5265,"text_color":"white","mb_lg":"","position":"position-relative","overflow":"overflow-hidden","anchor":"footer","className":"block-1618467995"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='#2e0761'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image='<?php echo esc_attr( $section_img_url ); ?>'  bg_image_id='5265'  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor='footer'  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined bg-custom-color text-white container-fluid position-relative overflow-hidden" style="background-color:#2e0761;background-image:url(<?php echo esc_attr( $section_img_url ); ?>);background-blend-mode:overlay;background-size:cover" id="footer"><!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","pt_lg":"6","pb_lg":"5","className":"block-1618467995"} -->
	[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg=''  pb_lg='5'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-6 pb-5 container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","position":"position-relative","className":"block-1618467995"} -->
		[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"6","bg_on_text":true,"text_color":"white","mt_lg":"n3","pt_lg":"3","pr_lg":"6","className":"block-1618467995"} -->
			[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='true'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='n3'  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='6'  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mt-n3 mb-3 pt-3 pe-6 col-12 col-md-6 col-lg-6 text-white col"><!-- wp:image {"id":5031,"width":"117px","sizeSlug":"full","linkDestination":"none"} -->
				<figure class="wp-block-image size-full is-resized"><img src="<?php echo esc_attr( $logo_img_url ); ?>" alt="" class="wp-image-5031" style="width:117px"/></figure>
				<!-- /wp:image -->

				<!-- wp:paragraph {"className":"mt-3","fontSize":"small"} -->
				<p class="mt-3 has-small-font-size">Lorem ipsum dolor sit amet, consectetur adipiscing elit, ut tincidunt magna diam vel ultricies velit elementum id.</p>
				<!-- /wp:paragraph -->

				<!-- wp:paragraph {"style":{"typography":{"fontSize":"0.8rem"}},"textColor":"octonary"} -->
				<p class="has-octonary-color has-text-color" style="font-size:0.8rem">Copyright © BlockStrap 2024. All rights reserved.</p>
				<!-- /wp:paragraph --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container -->

			<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"3","content":"","className":"block-1618467995"} -->
			[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 col-12 col-md-6 col-lg-3 col"><!-- wp:heading {"style":{"typography":{"fontSize":"1.3rem","fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white"} -->
				<h2 class="wp-block-heading has-white-color has-text-color has-link-color" style="font-size:1.3rem;font-style:normal;font-weight:700">About Us</h2>
				<!-- /wp:heading -->

				<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","flex_direction":"flex-column","mr_lg":"","ml_lg":"n3"} -->
				[bs_nav anchor=''  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto ms-lg-n3 flex-column"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Our Story","link_bg":"gray","text_color":"white","content":""} -->
						[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Our Story'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

						<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"add_gd_place","text":"Add Event","link_bg":"gray","text_color":"white","content":""} -->
						[bs_nav_item type='add_gd_place'  page_id=''  post_id=''  custom_url=''  text='Add Event'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

						<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Legal","text_color":"white","content":""} -->
						[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='Legal'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
				<!-- /wp:blockstrap/blockstrap-widget-nav --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container -->

			<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"3","text_color":"white","content":"","className":"block-1618467995"} -->
			[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 col-12 col-md-6 col-lg-3 text-white col"><!-- wp:heading {"style":{"typography":{"fontSize":"1.3rem","fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white"} -->
				<h2 class="wp-block-heading has-white-color has-text-color has-link-color" style="font-size:1.3rem;font-style:normal;font-weight:700">Contact Us</h2>
				<!-- /wp:heading -->

				<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","flex_direction":"flex-column","ml_lg":"n3","pl_lg":"0"} -->
				[bs_nav anchor=''  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto me-lg-0 ms-lg-n3 ps-0 flex-column"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"info@ayecode.io","icon_class":"far fa-envelope","link_bg":"white","text_color":"white","content":""} -->
						[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='info@ayecode.io'  icon_class='far fa-envelope'  icon_aria_label=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

						<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"+123 456 789","icon_class":"fa-solid fa-mobile-screen","link_bg":"white","text_color":"white","content":""} -->
						[bs_nav_item type='home'  page_id=''  post_id=''  custom_url=''  text='+123 456 789'  icon_class='fa-solid fa-mobile-screen'  icon_aria_label=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
				<!-- /wp:blockstrap/blockstrap-widget-nav -->

				<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"social-links","inside_navbar":"0","ml_lg":"n3"} -->
				[bs_nav anchor='social-links'  inside_navbar='0'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_social-links"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto me-lg-0 ms-lg-n3"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#facebook","icon_class":"fab fa-facebook","link_bg":"white","text_color":"white","content":""} -->
						[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#facebook'  text=''  icon_class='fab fa-facebook'  icon_aria_label=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

						<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#twriiter","icon_class":"fab fa-twitter","link_bg":"white","text_color":"white","content":""} -->
						[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#twriiter'  text=''  icon_class='fab fa-twitter'  icon_aria_label=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

						<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#instagram","icon_class":"fab fa-instagram","link_bg":"white","text_color":"white","content":""} -->
						[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#instagram'  text=''  icon_class='fab fa-instagram'  icon_aria_label=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
						<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
				<!-- /wp:blockstrap/blockstrap-widget-nav --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-scroll-top {"content":""} -->
[bs_scroll_top icon_class=''  color_class='outline-primary'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  shadow=''  display=''  display_md=''  display_lg=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-scroll-top -->
